version: '3'

services:
  db:
    image: mysql:5.7
    container_name: collection_db
    volumes:
      - ${PWD}/db_data:/var/lib/mysql
    ports: 
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collection
      MYSQL_USER: collection
      MYSQL_PASSWORD: collection

  phpmyadmin:
    container_name: collection_pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8222:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: collection
